# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libprolog

# >> macros
# << macros

Summary:    A convenience library Nokia policy engine prolog library
Version:    1.1.10
Release:    1
Group:      System/Resource Policy
License:    LGPLv2.1
URL:        https://github.com/nemomobile/libprolog
Source0:    %{name}-%{version}.tar.gz
Requires:   swi-prolog-library-core
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(swi-prolog)

%description
The prolog convenience library contains a small set of functions that
are supposed to make embedding the SWI-Prolog interpreter easier.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%autogen --disable-static
%configure --disable-static \
    --enable-extra-warnings

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/*.so.*
%{_datadir}/libprolog/*
%doc README COPYING INSTALL AUTHORS NEWS ChangeLog
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/prolog/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*
# << files devel
